<a href="https://colab.research.google.com/github/ClaudioAresu/TensorFlow/blob/main/00tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In this notebook, we're going to cover some of the most funndamental concepts of tensors using TensorFlow

More specifically, we're going to cover:

* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function( a way to speed up your regular Python functions)
* Using GPUs with TensorFlow (or TPUs)
* Exercuse to try for yourself

In [ ]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
#Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
#Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#Create a vetor
vector = tf.constant ([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#Check the number of dimensions
vector.ndim

1

In [ ]:
#Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10,7],
                      [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
#Check the number of dimensions
matrix.ndim

2

In [ ]:
#Create another matrix
matrix2 = tf.constant([[10.,7.],
                      [3.,2.],
                      [8., 9.]], dtype=tf.float16) #specify the dtype parameter
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#Check the number of dimensions
matrix2.ndim

2

In [ ]:
#Create a tensor
tensor = tf.constant([[[1, 2, 3,],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                      [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#Check the number of dimensions
tensor.ndim

3

What we've created so far:

* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
#Create the same tensor with tf.Variable() as aboe
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
#Change one of the elements in our changeable tensor
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

Random tensors are tensors of some arbitrary size wic contain radom numbers

In [ ]:
#Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42) #set the seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2
 

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

Shuffle the order of elements in a tensor

In [ ]:
#Shuffle a tensor (valuable for shuffling data so that the inherent order does not affect the outcome)
not_shuffled = tf.constant([[10, 7],
                           [3, 4],
                           [2, 5]])
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

In [ ]:

tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(not_shuffled, seed=42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

**Exercise: read through TensorFLow documentation on random seed generation: and practice writing 5 random tensors and shuffling them. 🧰

It looks like if we want our suhuffled tensors to be in the same order, we've got to use the global level in conjunction with the operation level random seed:
> Rule 4: "If both the global and the operation seed are set: Both seed are used in conjunction to determine the random numbers


In [ ]:
#Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#The main difference between NumPy arrays and TensorFLow tensors is that tensors can be run on a GPU much faster
import numpy as np
numpy_A = np.arange(1, 25, dtype= np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
#change np array to tensor
A = tf.constant(numpy_A, shape=(2, 3, 4))
B = tf.constant(numpy_A, shape=(3, 8))
C = tf.constant(numpy_A)

A, B, C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

In [ ]:
#Check Size
tf.size(A)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [ ]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
from tensorflow.python.ops.gen_array_ops import rank
#Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor as np:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor as np: 120


In [ ]:
homework_1 = tf.Variable([[[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]],
                           [[3, 2, 1],
                            [6, 5, 4],
                            [9, 8, 7]],
                          [[2, 1, 3],
                           [5, 4, 6],
                           [9, 7, 8]]], dtype=np.float32)
homework_1

<tf.Variable 'Variable:0' shape=(3, 3, 3) dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(homework_1)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(homework_1)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(homework_1)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(homework_1, seed=3)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(homework_1, seed=3)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]]], dtype=float32)>

In [ ]:
tf.random.shuffle(homework_1, seed=3)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1, seed=6)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1, seed=6)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1, seed=6)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1, seed=7)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]],

       [[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1, seed=8)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

In [ ]:
tf.random.set_seed(3)
tf.random.shuffle(homework_1, seed=9)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[2., 1., 3.],
        [5., 4., 6.],
        [9., 7., 8.]],

       [[3., 2., 1.],
        [6., 5., 4.],
        [9., 8., 7.]],

       [[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]], dtype=float32)>

Results without setting seed: shuffles the first dimension across the tensor, even if you shuffle again the result will BE THE SAME in the same instance.

Results setting only operation level seed: changes happen by shuffling the first dimension, result is random.

Results setting only global level seed:shuffles the first dimension across the tensor, even if you shuffle again the result will BE THE SAME in the same instance.

Results setting global level seed and a fixed operation level seed: shuffles the first dimension across the tensor, even if you shuffle again the result will BE THE SAME in the same instance but are different than a shuffled tensor using only the global level seed.

Results setting global level seed and different operation level seed: changes happen by shuffling the first dimension, result varies according to the operation level seed setted.




###Inndexing tensors

Tensors can be indexed just like python list

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one

rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:, :1, :1, :1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.ndim, rank_2_tensor.shape

(2, TensorShape([2, 2]))

In [ ]:
some_list[-1]

4

In [ ]:
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
#Add in extra dimension to our rank 2 tensor

rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# You can add values to a tensor using the addition operator( same goes for *, /, -)
tensor = tf.constant([[10, 7],
                      [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use the stensorflow built-in function too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

** Matrix Multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

In [ ]:
 #Matrix Multiplication in tensorflow
 
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Matrix Multiplication with python operator
tensor @ tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor.shape

TensorShape([2, 2])

In [ ]:
#Create a tensor (3,2)
X = tf.constant([[1, 2],
                 [3, 4],
                 [5,6]])
Y = tf.constant([[7, 8],
                 [9,10],
                 [11,12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
#Try to matrix multiply matrix of the same shape


Matrix Multiplication 📖 https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [ ]:
tf.reshape(Y, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:

tf.matmul(X,tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
#Create a model (specified to your problem)

model = tf.keras.Seqiential([
tf.keras.Input(shape=3,)),"relu"
tf.keras.layers.Dense(100, activation="relu"),
tf.keras.layers.Dense(100, activation="relu")
tf.keras.layers.Dense(100, activation="relu")
tf.keras.layers.Dense(100, activation=None)
])

#Compile the model
model.compile(loss=tf.keras.losses.mae,
              optimizer=tf.keras.optimizerss.Adam)